spring:
  application:
    name: BrainDissecting-SSR-version
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/brain-dissecting-ssr?createDatabaseIfNotExist=true
    username: ${db_username:}
    password: ${db_password:}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
  sql:
    init:
      mode: never
  mvc:
    hidden method:
      filter:
        enabled: true
server:
  error:
    whitelabel:
      enabled: true
doaj:
  api:
    url: "https://doaj.org/api/v3/search/articles/"



