spring:
  application:
    name: BrainDissecting-SSR-version
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
  sql:
    init:
      mode: never
  mvc:
    hidden-method:
      filter:
        enabled: true
server:
  error:
    whitelabel:
      enabled: true
logging:
  level:
    root: info
    org.hibernate.sql: warn
doaj:
  api:
    url: "https://doaj.org/api/v3/search/articles/"



