spring:
  application:
    name: BrainDissecting-SSR-version
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///brain_dissecting_db?cloudSqlInstance=${CLOUD_SQL_INSTANCE}&socketFactory=com.google.cloud.sql.mysql.SocketFactory
    username: ${db_username:}
    password: ${db_password:}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: false
  sql:
    init:
      mode: never
  mvc:
    hidden method:
      filter:
        enabled: true
server:
  error:
    whitelabel:
      enabled: true
logging:
  level:
    root: info
    org.hibernate.sql: warn
doaj:
  api:
    url: "https://doaj.org/api/v3/search/articles/"



